### ISSUE TITLE
Allow SMA changes with RCS.

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/StationKeeping#1]
A small cubesat without engine, but built-in RCS - I cannot change the SMA.

**Comment by linuxgurugamer** [comment]
I don't think the mod was designed with rcs in mind, but i'll take a look at it

**Comment by linuxgurugamer** [comment]
Assuming that a vessel has both RCS and engines, which would you expect to be used first for stationkeeping?

**Comment by Gordon-Dry** [comment]
RCS.
I don't think that the ISS fires up big engines for lifting the orbit twice a month.

**Comment by linuxgurugamer** [comment]
Just released
