### ISSUE TITLE
Tiny UI on high resolution displays

### ISSUE THREAD

**Issue by ToastyJacks** [linuxgurugamer/StationKeeping#2]
When using this mod at 4K, the UI is incredibly small and difficult to read. Some kind of way to adjust the GUI would come in useful for making this mod easier to use on these higher resolution displays. Here's an image for reference:
![Tiny UI](https://user-images.githubusercontent.com/48629785/84595542-55e66280-ae50-11ea-9067-1562c5f7a0fe.png)

**Comment by linuxgurugamer** [comment]
I do feel for you, I have a 4k monitor myself.
I'll see what I can do

**Comment by linuxgurugamer** [comment]
I just released a new version, try it with the stock skin and let me know how it is on your 4k monitor

**Comment by ToastyJacks** [comment]
The new version appears to be bigger and it's certainly easier to read the text (see screenshot). It should suffice as a temporary fix until a more permanent solution can be found. Thanks for your help!
![Slightly Larger](https://user-images.githubusercontent.com/48629785/84760783-70d7e480-afc0-11ea-8391-f3ee3b83ca15.png)
