### ISSUE TITLE
Stopped working with 1.12

### ISSUE THREAD

**Issue by Kash-420** [linuxgurugamer/StationKeeping#3]
I've been testing out various mods I use on 1.12 and it seems there's something causing issues with Station Keeping. When I go into the tracking station and select a vessel that is basically synchronized, SMA reads 1000 km, Altitude reads 0, Sync is N/A and the set Sync and set SMA buttons are greyed out.

Just wanted to post on here so you are aware, thanks for all the mods you've created and maintain.

**Comment by linuxgurugamer** [comment]
Appreciate it, could you post a log file, please.
also, posting on the forum would be helpful

**Comment by Kash-420** [comment]
So I went to create the log file and did a fresh save on a nice clean game file and I have no idea what changed, but it's working. So I hopped on a few other save files and it's working on them as well. I'm not running a lot of mods, but it would seem whatever the issue was it was caused by one of them and not Station Keeping. I'm very sorry for the waste of time!

**Comment by linuxgurugamer** [comment]
No problem, thank you for updating.
