### ISSUE TITLE
Electricity generation not accounted for

### ISSUE THREAD

**Issue by cabadam** [linuxgurugamer/StationKeeping#5]
I attempted to use this to get my relay into a steady orbit.  The relay has a single Dawn engine.  Due to a... design flaw... I failed to include any batteries on my relay, leaving only the 15 units that are stored in the RC-001S Remote Guideance Unit. 

Bailing the poor engineer out, the relay does have two gigantor XL solar arrays on it, which at a 4GM orbit around the sun, produce more than plenty of energy.  Unfortunately, the mod is looked at STORED units of fuel, and when attempting to set the SMA, it reports that the vehicle has insufficient fuel (even though I can burn nonstop manually due to the solar generation).  I'm not sure how easy/hard it would be, but for mistakes like this, it might be useful if it could account for that generation over time and allow the SMA correction to take place.

**Comment by linuxgurugamer** [comment]
Fixed in 0.2.3 release
